version: 2

builds:
  - binary: gh-auto-done
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  prerelease: auto
